# Generated by Django 6.0.2 on 2026-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_dailyusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyusage",
            name="qa_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
