# Generated by Django 6.0.2 on 2026-02-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_dailyusage_qa_count"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyUsage",
        ),
    ]
