# Generated by Django 6.0.2 on 2026-02-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="preview_text",
            field=models.TextField(blank=True),
        ),
    ]
