# Generated by Django 6.0.2 on 2026-02-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_preview_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisJob",
        ),
    ]
