# Generated by Django 6.0.2 on 2026-02-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_delete_analysisjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="analysis_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="analysis_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
