# Generated by Django 6.0.2 on 2026-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_analysis_json_document_analysis_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ai_raw",
            field=models.TextField(blank=True, default=""),
        ),
    ]
